[package]
name = "renet_transport_steam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renet = { path = "../renet", version = "0.0.9" }
steamworks = "0.9.0"
log = "0.4.11"
